// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7RiKYizIsJwQd3t5tGlU-Vcp1fOxmCVw',
    appId: '1:507823611338:web:6ecfb96a0c7bf1fb5b0333',
    messagingSenderId: '507823611338',
    projectId: 'edsushy-shop',
    authDomain: 'edsushy-shop.firebaseapp.com',
    storageBucket: 'edsushy-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CQ77QzO-9mIHepcbysE6t23hFT2aB1k',
    appId: '1:507823611338:android:dd110d0c50f90c3a5b0333',
    messagingSenderId: '507823611338',
    projectId: 'edsushy-shop',
    storageBucket: 'edsushy-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqweBwo2GD_WOUrQn4tTjrpZ5v5OZo-R4',
    appId: '1:507823611338:ios:ec2258724a8a97785b0333',
    messagingSenderId: '507823611338',
    projectId: 'edsushy-shop',
    storageBucket: 'edsushy-shop.firebasestorage.app',
    iosBundleId: 'com.example.edsushyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqweBwo2GD_WOUrQn4tTjrpZ5v5OZo-R4',
    appId: '1:507823611338:ios:ec2258724a8a97785b0333',
    messagingSenderId: '507823611338',
    projectId: 'edsushy-shop',
    storageBucket: 'edsushy-shop.firebasestorage.app',
    iosBundleId: 'com.example.edsushyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7RiKYizIsJwQd3t5tGlU-Vcp1fOxmCVw',
    appId: '1:507823611338:web:136d2c1c56419c845b0333',
    messagingSenderId: '507823611338',
    projectId: 'edsushy-shop',
    authDomain: 'edsushy-shop.firebaseapp.com',
    storageBucket: 'edsushy-shop.firebasestorage.app',
  );
}
